### ISSUE TITLE
SMV lexical error

### ISSUE THREAD

**Issue by nmacedo** [grayswandyr/electrod#2]
Solving model https://github.com/haslab/Electrum/blob/master/electrum/src/main/resources/models/electrum/peterson.ele with the first run command throws error

`[E001] 550.2-550.3: lexical error: SMV trace scanning: unknown variable: -`

**Comment by grayswandyr** [comment]
Thanks. Would you attach the .elo file?

**Comment by nmacedo** [comment]
There you go (renamed txt since elo was not allowed).
[00000.txt](https://github.com/grayswandyr/electrod/files/1985791/00000.txt)

**Comment by grayswandyr** [comment]
Fixed starting at release 0.1.6.

**Comment by grayswandyr** [comment]
The package in the opam repo is now updated to v0.1.6. You may `opam upgrade electrod`.
